version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - mongo.env
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: api-nodejs
    ports:
      - "3000:3000"
    env_file:
      - app.env
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
